Write-Host Testing Win32/Debug/allocator...
../Win32/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Debug/array...
../Win32/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Debug/atomic_t...
../Win32/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Debug/boolean...
../Win32/Debug/nkr_test_boolean.exe
Write-Host
Write-Host Testing Win32/Debug/charcoder...
../Win32/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Debug/concurrency...
../Win32/Debug/nkr_test_concurrency.exe
Write-Host
Write-Host Testing Win32/Debug/constant...
../Win32/Debug/nkr_test_constant.exe
Write-Host
Write-Host Testing Win32/Debug/cpp...
../Win32/Debug/nkr_test_cpp.exe
Write-Host
Write-Host Testing Win32/Debug/enumeration...
../Win32/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Debug/generic...
../Win32/Debug/nkr_test_generic.exe
Write-Host
Write-Host Testing Win32/Debug/hasher...
../Win32/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Debug/interface...
../Win32/Debug/nkr_test_interface.exe
Write-Host
Write-Host Testing Win32/Debug/macros...
../Win32/Debug/nkr_test_macros.exe
Write-Host
Write-Host Testing Win32/Debug/math...
../Win32/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Debug/maybe_t...
../Win32/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Debug/negatable...
../Win32/Debug/nkr_test_negatable.exe
Write-Host
Write-Host Testing Win32/Debug/none...
../Win32/Debug/nkr_test_none.exe
Write-Host
Write-Host Testing Win32/Debug/number...
../Win32/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Debug/optional...
../Win32/Debug/nkr_test_optional.exe
Write-Host
Write-Host Testing Win32/Debug/os...
../Win32/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Debug/pointer...
../Win32/Debug/nkr_test_pointer.exe
Write-Host
Write-Host Testing Win32/Debug/pointer_t...
../Win32/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Debug/positive...
../Win32/Debug/nkr_test_positive.exe
Write-Host
Write-Host Testing Win32/Debug/randomness...
../Win32/Debug/nkr_test_randomness.exe
Write-Host
Write-Host Testing Win32/Debug/regex_t...
../Win32/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Debug/string...
../Win32/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Debug/tr...
../Win32/Debug/nkr_test_tr.exe
Write-Host
Write-Host Testing Win32/Debug/tree...
../Win32/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Debug/tuple...
../Win32/Debug/nkr_test_tuple.exe
Write-Host
Write-Host Testing Win32/Debug/utils...
../Win32/Debug/nkr_test_utils.exe
Write-Host

Write-Host Testing Win32/Release/allocator...
../Win32/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Release/array...
../Win32/Release/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Release/atomic_t...
../Win32/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Release/boolean...
../Win32/Release/nkr_test_boolean.exe
Write-Host
Write-Host Testing Win32/Release/charcoder...
../Win32/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Release/concurrency...
../Win32/Release/nkr_test_concurrency.exe
Write-Host
Write-Host Testing Win32/Release/constant...
../Win32/Release/nkr_test_constant.exe
Write-Host
Write-Host Testing Win32/Release/cpp...
../Win32/Release/nkr_test_cpp.exe
Write-Host
Write-Host Testing Win32/Release/enumeration...
../Win32/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Release/generic...
../Win32/Release/nkr_test_generic.exe
Write-Host
Write-Host Testing Win32/Release/hasher...
../Win32/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Release/interface...
../Win32/Release/nkr_test_interface.exe
Write-Host
Write-Host Testing Win32/Release/macros...
../Win32/Release/nkr_test_macros.exe
Write-Host
Write-Host Testing Win32/Release/math...
../Win32/Release/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Release/maybe_t...
../Win32/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Release/negatable...
../Win32/Release/nkr_test_negatable.exe
Write-Host
Write-Host Testing Win32/Release/none...
../Win32/Release/nkr_test_none.exe
Write-Host
Write-Host Testing Win32/Release/number...
../Win32/Release/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Release/optional...
../Win32/Release/nkr_test_optional.exe
Write-Host
Write-Host Testing Win32/Release/os...
../Win32/Release/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Release/pointer...
../Win32/Release/nkr_test_pointer.exe
Write-Host
Write-Host Testing Win32/Release/pointer_t...
../Win32/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Release/positive...
../Win32/Release/nkr_test_positive.exe
Write-Host
Write-Host Testing Win32/Release/randomness...
../Win32/Release/nkr_test_randomness.exe
Write-Host
Write-Host Testing Win32/Release/regex_t...
../Win32/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Release/string...
../Win32/Release/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Release/tr...
../Win32/Release/nkr_test_tr.exe
Write-Host
Write-Host Testing Win32/Release/tree...
../Win32/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Release/tuple...
../Win32/Release/nkr_test_tuple.exe
Write-Host
Write-Host Testing Win32/Release/utils...
../Win32/Release/nkr_test_utils.exe
Write-Host

Write-Host Testing x64/Debug/allocator...
../x64/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Debug/array...
../x64/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Debug/atomic_t...
../x64/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Debug/boolean...
../x64/Debug/nkr_test_boolean.exe
Write-Host
Write-Host Testing x64/Debug/charcoder...
../x64/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Debug/concurrency...
../x64/Debug/nkr_test_concurrency.exe
Write-Host
Write-Host Testing x64/Debug/constant...
../x64/Debug/nkr_test_constant.exe
Write-Host
Write-Host Testing x64/Debug/cpp...
../x64/Debug/nkr_test_cpp.exe
Write-Host
Write-Host Testing x64/Debug/enumeration...
../x64/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Debug/generic...
../x64/Debug/nkr_test_generic.exe
Write-Host
Write-Host Testing x64/Debug/hasher...
../x64/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Debug/interface...
../x64/Debug/nkr_test_interface.exe
Write-Host
Write-Host Testing x64/Debug/macros...
../x64/Debug/nkr_test_macros.exe
Write-Host
Write-Host Testing x64/Debug/math...
../x64/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Debug/maybe_t...
../x64/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Debug/negatable...
../x64/Debug/nkr_test_negatable.exe
Write-Host
Write-Host Testing x64/Debug/none...
../x64/Debug/nkr_test_none.exe
Write-Host
Write-Host Testing x64/Debug/number...
../x64/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Debug/optional...
../x64/Debug/nkr_test_optional.exe
Write-Host
Write-Host Testing x64/Debug/os...
../x64/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Debug/pointer...
../x64/Debug/nkr_test_pointer.exe
Write-Host
Write-Host Testing x64/Debug/pointer_t...
../x64/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Debug/positive...
../x64/Debug/nkr_test_positive.exe
Write-Host
Write-Host Testing x64/Debug/randomness...
../x64/Debug/nkr_test_randomness.exe
Write-Host
Write-Host Testing x64/Debug/regex_t...
../x64/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Debug/string...
../x64/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Debug/tr...
../x64/Debug/nkr_test_tr.exe
Write-Host
Write-Host Testing x64/Debug/tree...
../x64/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Debug/tuple...
../x64/Debug/nkr_test_tuple.exe
Write-Host
Write-Host Testing x64/Debug/utils...
../x64/Debug/nkr_test_utils.exe
Write-Host

Write-Host Testing x64/Release/allocator...
../x64/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Release/array...
../x64/Release/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Release/atomic_t...
../x64/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Release/boolean...
../x64/Release/nkr_test_boolean.exe
Write-Host
Write-Host Testing x64/Release/charcoder...
../x64/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Release/concurrency...
../x64/Release/nkr_test_concurrency.exe
Write-Host
Write-Host Testing x64/Release/constant...
../x64/Release/nkr_test_constant.exe
Write-Host
Write-Host Testing x64/Release/cpp...
../x64/Release/nkr_test_cpp.exe
Write-Host
Write-Host Testing x64/Release/enumeration...
../x64/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Release/generic...
../x64/Release/nkr_test_generic.exe
Write-Host
Write-Host Testing x64/Release/hasher...
../x64/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Release/interface...
../x64/Release/nkr_test_interface.exe
Write-Host
Write-Host Testing x64/Release/macros...
../x64/Release/nkr_test_macros.exe
Write-Host
Write-Host Testing x64/Release/math...
../x64/Release/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Release/maybe_t...
../x64/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Release/negatable...
../x64/Release/nkr_test_negatable.exe
Write-Host
Write-Host Testing x64/Release/none...
../x64/Release/nkr_test_none.exe
Write-Host
Write-Host Testing x64/Release/number...
../x64/Release/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Release/optional...
../x64/Release/nkr_test_optional.exe
Write-Host
Write-Host Testing x64/Release/os...
../x64/Release/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Release/pointer...
../x64/Release/nkr_test_pointer.exe
Write-Host
Write-Host Testing x64/Release/pointer_t...
../x64/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Release/positive...
../x64/Release/nkr_test_positive.exe
Write-Host
Write-Host Testing x64/Release/randomness...
../x64/Release/nkr_test_randomness.exe
Write-Host
Write-Host Testing x64/Release/regex_t...
../x64/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Release/string...
../x64/Release/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Release/tr...
../x64/Release/nkr_test_tr.exe
Write-Host
Write-Host Testing x64/Release/tree...
../x64/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Release/tuple...
../x64/Release/nkr_test_tuple.exe
Write-Host
Write-Host Testing x64/Release/utils...
../x64/Release/nkr_test_utils.exe
Write-Host

Write-Host press any key to continue...
Write-Host

Read-Host
