Write-Host Testing Win32/Debug/allocator...
../Win32/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Debug/array...
../Win32/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Debug/atomic_t...
../Win32/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Debug/boolean...
../Win32/Debug/nkr_test_boolean.exe
Write-Host
Write-Host Testing Win32/Debug/charcoder...
../Win32/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Debug/concurrency...
../Win32/Debug/nkr_test_concurrency.exe
Write-Host
Write-Host Testing Win32/Debug/constant...
../Win32/Debug/nkr_test_constant.exe
Write-Host
Write-Host Testing Win32/Debug/cpp...
../Win32/Debug/nkr_test_cpp.exe
Write-Host
Write-Host Testing Win32/Debug/enumeration...
../Win32/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Debug/generic...
../Win32/Debug/nkr_test_generic.exe
Write-Host
Write-Host Testing Win32/Debug/hasher...
../Win32/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Debug/interface...
../Win32/Debug/nkr_test_interface.exe
Write-Host
Write-Host Testing Win32/Debug/macros...
../Win32/Debug/nkr_test_macros.exe
Write-Host
Write-Host Testing Win32/Debug/math...
../Win32/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Debug/maybe_t...
../Win32/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Debug/negatable...
../Win32/Debug/nkr_test_negatable.exe
Write-Host
Write-Host Testing Win32/Debug/none...
../Win32/Debug/nkr_test_none.exe
Write-Host
Write-Host Testing Win32/Debug/number...
../Win32/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Debug/optional...
../Win32/Debug/nkr_test_optional.exe
Write-Host
Write-Host Testing Win32/Debug/os...
../Win32/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Debug/pointer...
../Win32/Debug/nkr_test_pointer.exe
Write-Host
Write-Host Testing Win32/Debug/pointer_t...
../Win32/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Debug/positive...
../Win32/Debug/nkr_test_positive.exe
Write-Host
Write-Host Testing Win32/Debug/randomness...
../Win32/Debug/nkr_test_randomness.exe
Write-Host
Write-Host Testing Win32/Debug/regex_t...
../Win32/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Debug/string...
../Win32/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Debug/tr...
../Win32/Debug/nkr_test_tr.exe
Write-Host
Write-Host Testing Win32/Debug/tree...
../Win32/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Debug/tuple...
../Win32/Debug/nkr_test_tuple.exe
Write-Host
Write-Host Testing Win32/Debug/utils...
../Win32/Debug/nkr_test_utils.exe
Write-Host
Write-Host press any key to continue...
Write-Host
Read-Host
