Write-Host Testing Win32/Release/allocator...
../Win32/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Release/array...
../Win32/Release/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Release/atomic_t...
../Win32/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Release/boolean...
../Win32/Release/nkr_test_boolean.exe
Write-Host
Write-Host Testing Win32/Release/charcoder...
../Win32/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Release/concurrency...
../Win32/Release/nkr_test_concurrency.exe
Write-Host
Write-Host Testing Win32/Release/constant...
../Win32/Release/nkr_test_constant.exe
Write-Host
Write-Host Testing Win32/Release/cpp...
../Win32/Release/nkr_test_cpp.exe
Write-Host
Write-Host Testing Win32/Release/enumeration...
../Win32/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Release/generic...
../Win32/Release/nkr_test_generic.exe
Write-Host
Write-Host Testing Win32/Release/hasher...
../Win32/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Release/interface...
../Win32/Release/nkr_test_interface.exe
Write-Host
Write-Host Testing Win32/Release/macros...
../Win32/Release/nkr_test_macros.exe
Write-Host
Write-Host Testing Win32/Release/math...
../Win32/Release/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Release/maybe_t...
../Win32/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Release/negatable...
../Win32/Release/nkr_test_negatable.exe
Write-Host
Write-Host Testing Win32/Release/none...
../Win32/Release/nkr_test_none.exe
Write-Host
Write-Host Testing Win32/Release/number...
../Win32/Release/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Release/optional...
../Win32/Release/nkr_test_optional.exe
Write-Host
Write-Host Testing Win32/Release/os...
../Win32/Release/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Release/pointer...
../Win32/Release/nkr_test_pointer.exe
Write-Host
Write-Host Testing Win32/Release/pointer_t...
../Win32/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Release/positive...
../Win32/Release/nkr_test_positive.exe
Write-Host
Write-Host Testing Win32/Release/randomness...
../Win32/Release/nkr_test_randomness.exe
Write-Host
Write-Host Testing Win32/Release/regex_t...
../Win32/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Release/string...
../Win32/Release/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Release/tr...
../Win32/Release/nkr_test_tr.exe
Write-Host
Write-Host Testing Win32/Release/tree...
../Win32/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Release/tuple...
../Win32/Release/nkr_test_tuple.exe
Write-Host
Write-Host Testing Win32/Release/utils...
../Win32/Release/nkr_test_utils.exe
Write-Host
Write-Host press any key to continue...
Write-Host
Read-Host
