Write-Host Testing x64/Debug/allocator...
../x64/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Debug/array...
../x64/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Debug/atomic_t...
../x64/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Debug/boolean...
../x64/Debug/nkr_test_boolean.exe
Write-Host
Write-Host Testing x64/Debug/charcoder...
../x64/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Debug/concurrency...
../x64/Debug/nkr_test_concurrency.exe
Write-Host
Write-Host Testing x64/Debug/constant...
../x64/Debug/nkr_test_constant.exe
Write-Host
Write-Host Testing x64/Debug/cpp...
../x64/Debug/nkr_test_cpp.exe
Write-Host
Write-Host Testing x64/Debug/enumeration...
../x64/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Debug/generic...
../x64/Debug/nkr_test_generic.exe
Write-Host
Write-Host Testing x64/Debug/hasher...
../x64/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Debug/interface...
../x64/Debug/nkr_test_interface.exe
Write-Host
Write-Host Testing x64/Debug/macros...
../x64/Debug/nkr_test_macros.exe
Write-Host
Write-Host Testing x64/Debug/math...
../x64/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Debug/maybe_t...
../x64/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Debug/negatable...
../x64/Debug/nkr_test_negatable.exe
Write-Host
Write-Host Testing x64/Debug/none...
../x64/Debug/nkr_test_none.exe
Write-Host
Write-Host Testing x64/Debug/number...
../x64/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Debug/optional...
../x64/Debug/nkr_test_optional.exe
Write-Host
Write-Host Testing x64/Debug/os...
../x64/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Debug/pointer...
../x64/Debug/nkr_test_pointer.exe
Write-Host
Write-Host Testing x64/Debug/pointer_t...
../x64/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Debug/positive...
../x64/Debug/nkr_test_positive.exe
Write-Host
Write-Host Testing x64/Debug/randomness...
../x64/Debug/nkr_test_randomness.exe
Write-Host
Write-Host Testing x64/Debug/regex_t...
../x64/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Debug/string...
../x64/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Debug/tr...
../x64/Debug/nkr_test_tr.exe
Write-Host
Write-Host Testing x64/Debug/tree...
../x64/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Debug/tuple...
../x64/Debug/nkr_test_tuple.exe
Write-Host
Write-Host Testing x64/Debug/utils...
../x64/Debug/nkr_test_utils.exe
Write-Host
Write-Host press any key to continue...
Write-Host
Read-Host
