Write-Host Testing Win32/Debug/allocator...
../Win32/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Debug/array...
../Win32/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Debug/atomic_t...
../Win32/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Debug/bool_t...
../Win32/Debug/nkr_test_bool_t.exe
Write-Host
Write-Host Testing Win32/Debug/charcoder...
../Win32/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Debug/enumeration...
../Win32/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Debug/hasher...
../Win32/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Debug/math...
../Win32/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Debug/maybe_t...
../Win32/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Debug/number...
../Win32/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Debug/os...
../Win32/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Debug/pointer_t...
../Win32/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Debug/regex_t...
../Win32/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Debug/string...
../Win32/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Debug/traits...
../Win32/Debug/nkr_test_traits.exe
Write-Host
Write-Host Testing Win32/Debug/tree...
../Win32/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Debug/utils...
../Win32/Debug/nkr_test_utils.exe
Write-Host

Write-Host Testing Win32/Release/allocator...
../Win32/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing Win32/Release/array...
../Win32/Release/nkr_test_array.exe
Write-Host
Write-Host Testing Win32/Release/atomic_t...
../Win32/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing Win32/Release/bool_t...
../Win32/Release/nkr_test_bool_t.exe
Write-Host
Write-Host Testing Win32/Release/charcoder...
../Win32/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing Win32/Release/enumeration...
../Win32/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing Win32/Release/hasher...
../Win32/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing Win32/Release/math...
../Win32/Release/nkr_test_math.exe
Write-Host
Write-Host Testing Win32/Release/maybe_t...
../Win32/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing Win32/Release/number...
../Win32/Release/nkr_test_number.exe
Write-Host
Write-Host Testing Win32/Release/os...
../Win32/Release/nkr_test_os.exe
Write-Host
Write-Host Testing Win32/Release/pointer_t...
../Win32/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing Win32/Release/regex_t...
../Win32/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing Win32/Release/string...
../Win32/Release/nkr_test_string.exe
Write-Host
Write-Host Testing Win32/Release/traits...
../Win32/Release/nkr_test_traits.exe
Write-Host
Write-Host Testing Win32/Release/tree...
../Win32/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing Win32/Release/utils...
../Win32/Release/nkr_test_utils.exe
Write-Host

Write-Host Testing x64/Debug/allocator...
../x64/Debug/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Debug/array...
../x64/Debug/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Debug/atomic_t...
../x64/Debug/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Debug/bool_t...
../x64/Debug/nkr_test_bool_t.exe
Write-Host
Write-Host Testing x64/Debug/charcoder...
../x64/Debug/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Debug/enumeration...
../x64/Debug/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Debug/hasher...
../x64/Debug/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Debug/math...
../x64/Debug/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Debug/maybe_t...
../x64/Debug/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Debug/number...
../x64/Debug/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Debug/os...
../x64/Debug/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Debug/pointer_t...
../x64/Debug/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Debug/regex_t...
../x64/Debug/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Debug/string...
../x64/Debug/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Debug/traits...
../x64/Debug/nkr_test_traits.exe
Write-Host
Write-Host Testing x64/Debug/tree...
../x64/Debug/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Debug/utils...
../x64/Debug/nkr_test_utils.exe
Write-Host

Write-Host Testing x64/Release/allocator...
../x64/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Release/array...
../x64/Release/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Release/atomic_t...
../x64/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Release/bool_t...
../x64/Release/nkr_test_bool_t.exe
Write-Host
Write-Host Testing x64/Release/charcoder...
../x64/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Release/enumeration...
../x64/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Release/hasher...
../x64/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Release/math...
../x64/Release/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Release/maybe_t...
../x64/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Release/number...
../x64/Release/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Release/os...
../x64/Release/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Release/pointer_t...
../x64/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Release/regex_t...
../x64/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Release/string...
../x64/Release/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Release/traits...
../x64/Release/nkr_test_traits.exe
Write-Host
Write-Host Testing x64/Release/tree...
../x64/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Release/utils...
../x64/Release/nkr_test_utils.exe
Write-Host

Write-Host press any key to continue...
Write-Host

Read-Host
