Write-Host Testing x64/Release/allocator...
../x64/Release/nkr_test_allocator.exe
Write-Host
Write-Host Testing x64/Release/array...
../x64/Release/nkr_test_array.exe
Write-Host
Write-Host Testing x64/Release/atomic_t...
../x64/Release/nkr_test_atomic_t.exe
Write-Host
Write-Host Testing x64/Release/boolean...
../x64/Release/nkr_test_boolean.exe
Write-Host
Write-Host Testing x64/Release/charcoder...
../x64/Release/nkr_test_charcoder.exe
Write-Host
Write-Host Testing x64/Release/concurrency...
../x64/Release/nkr_test_concurrency.exe
Write-Host
Write-Host Testing x64/Release/constant...
../x64/Release/nkr_test_constant.exe
Write-Host
Write-Host Testing x64/Release/cpp...
../x64/Release/nkr_test_cpp.exe
Write-Host
Write-Host Testing x64/Release/enumeration...
../x64/Release/nkr_test_enumeration.exe
Write-Host
Write-Host Testing x64/Release/generic...
../x64/Release/nkr_test_generic.exe
Write-Host
Write-Host Testing x64/Release/hasher...
../x64/Release/nkr_test_hasher.exe
Write-Host
Write-Host Testing x64/Release/interface...
../x64/Release/nkr_test_interface.exe
Write-Host
Write-Host Testing x64/Release/macros...
../x64/Release/nkr_test_macros.exe
Write-Host
Write-Host Testing x64/Release/math...
../x64/Release/nkr_test_math.exe
Write-Host
Write-Host Testing x64/Release/maybe_t...
../x64/Release/nkr_test_maybe_t.exe
Write-Host
Write-Host Testing x64/Release/negatable...
../x64/Release/nkr_test_negatable.exe
Write-Host
Write-Host Testing x64/Release/none...
../x64/Release/nkr_test_none.exe
Write-Host
Write-Host Testing x64/Release/number...
../x64/Release/nkr_test_number.exe
Write-Host
Write-Host Testing x64/Release/optional...
../x64/Release/nkr_test_optional.exe
Write-Host
Write-Host Testing x64/Release/os...
../x64/Release/nkr_test_os.exe
Write-Host
Write-Host Testing x64/Release/pointer...
../x64/Release/nkr_test_pointer.exe
Write-Host
Write-Host Testing x64/Release/pointer_t...
../x64/Release/nkr_test_pointer_t.exe
Write-Host
Write-Host Testing x64/Release/positive...
../x64/Release/nkr_test_positive.exe
Write-Host
Write-Host Testing x64/Release/randomness...
../x64/Release/nkr_test_randomness.exe
Write-Host
Write-Host Testing x64/Release/regex_t...
../x64/Release/nkr_test_regex_t.exe
Write-Host
Write-Host Testing x64/Release/string...
../x64/Release/nkr_test_string.exe
Write-Host
Write-Host Testing x64/Release/tr...
../x64/Release/nkr_test_tr.exe
Write-Host
Write-Host Testing x64/Release/tree...
../x64/Release/nkr_test_tree.exe
Write-Host
Write-Host Testing x64/Release/tuple...
../x64/Release/nkr_test_tuple.exe
Write-Host
Write-Host Testing x64/Release/utils...
../x64/Release/nkr_test_utils.exe
Write-Host
Write-Host press any key to continue...
Write-Host
Read-Host
